name: Deploy Backend to VPS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check AWS CLI version
        run: aws --version

      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Decode .env base64 string and restore it
      - name: Decode .env file
        run: |
          echo "${{ secrets.ENV_BASE64_FE }}" | base64 --decode > ./client/.env.local

      # Step 3: Determine Docker Image Tag
      - name: Set Docker image tag
        id: docker_tag
        run: |
          if [ "${{ github.event_name }}" == "push" ] && [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "tag=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT
          elif [ "${{ github.event_name }}" == "push" ] && [[ "${{ github.ref }}" == refs/tags/v* ]]; then
            tag_version=$(echo "${{ github.ref }}" | sed -e 's/refs\/tags\/v//')
            echo "tag=v$tag_version" >> $GITHUB_OUTPUT
          else
            echo "tag=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT
          fi

      # Step 4: Build Docker image directly with inline variables
      - name: Build Docker image
        run: |
          # Use direct substitution in command
          docker build --no-cache -t "${{ secrets.DOCKER_HUB_USERNAME }}/shopware-client:${{ steps.docker_tag.outputs.tag }}" -f ./client/Dockerfile ./client

      # Step 5: Log in to DockerHub using PAT
      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_HUB_PAT }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      # Step 6: Push Docker image to DockerHub
      - name: Push Docker image to DockerHub
        run: docker push "${{ secrets.DOCKER_HUB_USERNAME }}/shopware-client:${{ steps.docker_tag.outputs.tag }}"

      # Step 7: SSH into the VPS and deploy
      - name: Deploy to VPS
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          # Set these to simple variables that won't be split
          DOCKER_IMAGE: "${{ secrets.DOCKER_HUB_USERNAME }}/shopware-client:${{ steps.docker_tag.outputs.tag }}"
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key
          chmod 600 private_key

          # Print the image name for debugging
          echo "Deploying image: $DOCKER_IMAGE"
          
          ssh -i private_key -o StrictHostKeyChecking=no root@116.202.27.145 "
            docker pull $DOCKER_IMAGE
            docker stop shopware-client || true
            docker rm shopware-client || true
            docker run -d --name shopware-client --network shopware-client -p 3000 $DOCKER_IMAGE
            docker image prune -a -f
          "

      # Step 8: Clean up
      - name: Clean up private key
        run: rm -f private_key