name: Deploy Backend to Hostinger VPS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check AWS CLI version
        run: aws --version

      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Docker and Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Decode .env base64 string and restore it
      - name: Decode .env file
        run: |
          echo "${{ secrets.ENV_BASE64_FE }}" | base64 --decode > ./client/.env.local
          # cat ./apps/api/.env

      # Step 4: Determine Docker Image Tag
      - name: Set Docker image tag
        id: docker_tag
        run: |
          if [ "${{ github.event_name }}" == "push" ] && [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "tag=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT
          elif [ "${{ github.event_name }}" == "push" ] && [[ "${{ github.ref }}" == refs/tags/v* ]]; then
            tag_version=$(echo "${{ github.ref }}" | sed -e 's/refs\/tags\/v//')
            echo "tag=v$tag_version" >> $GITHUB_OUTPUT
          else
            echo "tag=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT
          fi

      # Step 5: Build Docker image with the standard docker build
      - name: Build Docker image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          IMAGE_TAG: ${{ steps.docker_tag.outputs.tag }}
        run: |
          # Print the command for debugging
          echo "Building image: ${DOCKER_USERNAME}/shopware-client:${IMAGE_TAG}"
          # Use the standard docker command instead of buildx
          docker build --no-cache -t ${DOCKER_USERNAME}/shopware-client:${IMAGE_TAG} -f ./client/Dockerfile ./client

      # Step 6: Log in to DockerHub using PAT
      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_HUB_PAT }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      # Step 7: Push Docker image to DockerHub
      - name: Push Docker image to DockerHub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          IMAGE_TAG: ${{ steps.docker_tag.outputs.tag }}
        run: docker push ${DOCKER_USERNAME}/shopware-client:${IMAGE_TAG}

      # Step 8: SSH into the VPS and deploy
      - name: Deploy to VPS
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          IMAGE_TAG: ${{ steps.docker_tag.outputs.tag }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key
          chmod 600 private_key

          # SSH into VPS and update the Docker container
          ssh -i private_key -o StrictHostKeyChecking=no root@116.202.27.145 "
            docker pull ${DOCKER_USERNAME}/shopware-client:${IMAGE_TAG}
            docker stop shopware-client || true
            docker rm shopware-client || true
            docker run -d --name shopware-client --network shopware-client -p 3000 ${DOCKER_USERNAME}/shopware-client:${IMAGE_TAG}
          
            docker image prune -a -f
          "

      # Step 9: Clean up
      - name: Clean up private key
        run: rm -f private_key